### ISSUE TITLE
Debug issue getting pets' photos

### ISSUE THREAD

**Issue by mwleeds** [CodeforBirmingham/CutePets#1]
For some reason, `rake tweet_pet` is failing and I don't know enough Ruby to debug it. Here's the stacktrace:

```
** Invoke tweet_pet (first_time)
** Execute tweet_pet
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/app/lib/cute_pets/pet_fetcher.rb:110:in `get_photo'
/app/lib/cute_pets/pet_fetcher.rb:26:in `get_petfinder_pet'
/app/lib/cute_pets.rb:12:in `post_pet'
/app/Rakefile:10:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/app/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/app/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/app/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => tweet_pet
```

**Comment by davidgrieser** [comment]
So that is coming from the code [here](https://github.com/CodeforBirmingham/CutePets/blob/master/lib/cute_pets/pet_fetcher.rb#L26)

Based on the code, my first guess is `ENV.fetch('petfinder_key')` is not setup.

``` .ruby
  def get_petfinder_pet()
    uri = URI('http://api.petfinder.com/pet.getRandom')
    params = {
      format:    'json',
      key:        ENV.fetch('petfinder_key'),
      shelterid:  get_petfinder_shelter_id,
      output:    'full'
    }
    uri.query = URI.encode_www_form(params)
    response = Net::HTTP.get_response(uri)

    if response.kind_of? Net::HTTPSuccess
      json = JSON.parse(response.body)
      pet_json  = json['petfinder']['pet']
      {
        pic:   get_photo(pet_json),
        link:  "https://www.petfinder.com/petdetail/#{pet_json['id']['$t']}",
        name:  pet_json['name']['$t'].capitalize,
        description: [get_petfinder_option(pet_json['options']), get_petfinder_sex(pet_json['sex']['$t']),  get_petfinder_breed(pet_json['breeds'])].compact.join(' ').downcase
      }
```

**Comment by davidgrieser** [comment]
When accessing that URL directly, you get the following response:

``` .xml
<?xml version="1.0" encoding="iso-8859-1"?>

<petfinder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://api.petfinder.com/schemas/0.9/petfinder.xsd">
 <header>
  <version>0.1</version>
  <timestamp>2015-07-16T17:54:30Z</timestamp>
  <status>
   <code>300</code>
   <message>unauthorized key</message>
  </status>
 </header>
</petfinder>
```

So the code doesn't handle that scenario at all.

**Comment by mwleeds** [comment]
I actually just figured out the problem: the shelter I chose (GBHS) opted out of the API service so the response looked like this:

```
{
  "@encoding": "iso-8859-1",
  "@version": "1.0",
  "petfinder": {
    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
    "header": {
      "timestamp": {
        "$t": "2015-07-16T17:10:05Z"
      },
      "status": {
        "message": {
          "$t": "shelter opt-out"
        },
        "code": {
          "$t": "300"
        }
      },
      "version": {
        "$t": "0.1"
      }
    },
    "@xsi:noNamespaceSchemaLocation": "http://api.petfinder.com/schemas/0.9/petfinder.xsd"
  }
}
```

but there was no check in the code for that situation.

I added a check [here](https://github.com/codeforamerica/CutePets/pull/32) but now I have to get the CI bot to agree.
